version: '3.8'

services:
  oracle-db:
    image: doctorkirk/oracle-19c
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=asif
      - ORACLE_PWD=asif
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s SYSTEM/YourPassword123@//localhost:1521/ORCLCDB"]
      interval: 1m
      timeout: 30s
      retries: 3

volumes:
  oracle-data:

