version: '3.8'

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Thesnake7!
    volumes:
      - ./mysql_data:/var/lib/mysql  # After run, add permissions: chmod -R 777 ./mysql_data and /usr/bin is a local client
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-container  # Use the hostname of the MySQL container
      PMA_PORT: 3306
    networks:
      - app-network
    depends_on:
      - mysql-container

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./kafka_data:/bitnami/kafka      # After run, add permissions: chmod -R 777 ./kafka_data 
      - ./kafka_logs:/opt/bitnami/kafka/logs    # After run, add permissions: chmod -R 777 ./kafka_logs       

networks:
  app-network:
    driver: bridge
